name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

env:
  sample_image_url: https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg420exif.jpg

jobs:
  test-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: macos-latest
            cc: clang
    steps:
      - uses: actions/checkout@v3
      - run: curl ${{ env.sample_image_url }} -o sample.jpg
      - run: ${{ matrix.cc }} jpeg.c -o jpeg && ./jpeg

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl ${{ env.sample_image_url }} -o sample.jpg
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cl jpeg.c && ./jpeg
