name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v3
      - &download_image
        name: Download sample image
        run: curl https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg420exif.jpg -o sample.jpg
      - name: Compile and Run
        run: gcc jpeg.c -o jpeg && ./jpeg

  test-macos:
    runs-on: macos-latest
    steps:
      - *checkout
      - *download_image
      - name: Compile and Run
        run: clang jpeg.c -o jpeg && ./jpeg

  test-windows:
    runs-on: windows-latest
    steps:
      - *checkout
      - *download_image
      - name: Setup MSVC on Windows
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compile and Run
        run: cl jpeg.c && ./jpeg
