name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

env:
  sample_image_url: https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg420exif.jpg

jobs:
  test-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: macos-latest
            cc: clang
    steps:
      - uses: actions/checkout@v3
      - run: curl ${{ env.sample_image_url }} -o sample.jpg
      - run: ${{ matrix.cc }} -c -fPIC jpeg.c -o jpeg.o && ar rcs libjpeg_foo.a jpeg.o
      - run: ${{ matrix.cc }} test.c -o test -lm -ljpeg_foo -L. && ./test sample.jpg
      # - run: |
      #   ${{ matrix.cc }} jpeg.c -o jpeg.o -lm -O3 -ffast-math && ar rcs libjpeg_foo.a jpeg.o
      #   ${{ matrix.cc }} test.c -o test -ljpeg_foo -L. && ./test sample.jpg

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl ${{ env.sample_image_url }} -o sample.jpg
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cl jpeg.c && ./jpeg sample.jpg
      - run: cl jpeg.c /O2 /fp:fast && ./jpeg sample.jpg
